//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDesarroloAOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public int IDEMPLEADOS { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string DNI { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string SEXO { get; set; }
        public string TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
