//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDesarroloAOE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTAS()
        {
            this.REGISTRO = new HashSet<REGISTRO>();
        }
    
        public int IDVENTAS { get; set; }
        public Nullable<System.DateTime> FEC_VENT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> IDPRODUCTOS { get; set; }
        public Nullable<int> IDEMPLEADOS { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO> REGISTRO { get; set; }
    }
}
